"""Domain models shared by the learning graphs."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field


IncidentCategory = Literal[
    "NORMAL",
    "THREAD_POOL",
    "DATASOURCE_POOL",
    "DEPLOYMENT",
    "UNKNOWN",
]

RemediationActionType = Literal[
    "NONE",
    "SET_THREAD_POOL_MAX_THREADS",
    "SET_DATASOURCE_MAX_POOL_SIZE",
    "RESTART_DEPLOYMENT",
    "RELOAD_SERVER",
]


class LogClassification(BaseModel):
    """Structured result produced by Gemini for a block of JBoss-like logs."""

    incident_detected: bool = Field(
        description="Whether the log evidence suggests an operational incident."
    )
    category: IncidentCategory = Field(
        description="The single best category supported by the supplied log lines."
    )
    confidence: float = Field(ge=0.0, le=1.0)
    summary: str = Field(min_length=1)
    evidence: list[str] = Field(default_factory=list)


class RemediationAction(BaseModel):
    """Untrusted remediation proposal generated by the diagnosis LLM.

    Business-rule validation is intentionally performed later by risk_policy.py.
    This schema only constrains the *shape* of the LLM output.
    """

    type: RemediationActionType
    current_value: int | None = None
    proposed_value: int | None = None
    deployment_name: str | None = None
    rationale: str = Field(min_length=1)


class IncidentDiagnosis(BaseModel):
    """Structured diagnosis produced after the read-only investigation loop."""

    root_cause: str = Field(min_length=1)
    confidence: float = Field(ge=0.0, le=1.0)
    reason: str = Field(min_length=1)
    recommended_action: RemediationAction


class ApprovalResponse(BaseModel):
    """JSON-serializable value supplied through Command(resume=...)."""

    decision: Literal["approve", "reject", "edit_and_approve"]
    proposed_value: int | None = None


class ToolEvidence(BaseModel):
    """Normalized evidence record persisted in IncidentState."""

    tool_name: str
    content: Any
